name = "vietanhrs/lucky-ada"
version = "0.0.0"
compiler = "v1.1.22"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'vietanhrs/lucky-ada'"

[repository]
user = "vietanhrs"
project = "lucky-ada"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.1"
source = "github"

[config]
